### ISSUE TITLE
Sidebar icons oversized in Firefox (59.0.2, MacOS)

### ISSUE THREAD

**Issue by theangryangel** [reduction-admin/react-reduction#11]
Screenshot attached. Sorry I've not had any time to look at why. Thought it would be worth mentioning :) 

<img width="362" alt="screen shot 2018-05-09 at 09 33 54" src="https://user-images.githubusercontent.com/309967/39804519-2029ad5a-536c-11e8-8e33-745714537ac1.png">

**Comment by simsim0709** [comment]
Thanks a lot. I had never checked this out with firefox.

Firefox doesn't support `rem` unit for `svg` on width and height attributes.
It's weird it's working on `style` and `class` attributes, though.

Anyway, I appreciate it!
