### ISSUE TITLE
Dashboard Horizontal Avatar List Flicker

### ISSUE THREAD

**Issue by HITISINHA** [reduction-admin/react-reduction#29]
While the user hovers over each of the avatar from the Horizontal Avatar List on the Dashboard,  if the hover is in the lower 50% of the circle of Avatar, the tooltip goes on flickering and eventually, the pages gets stuck. I have resolved the same, using minimal independent, modular changes. Please merge if it is suitable.

**Comment by simsim0709** [comment]
#30 

It was already merged.

Thanks again @HITISINHA 👍
