### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by Nimitt3** [reduction-admin/react-reduction#34]
When taking a build using "npm run build" and placing the Build in Root of Tomcat and running it. It gives 404 on requests **https://reduction-admin.github.io/react-reduction/static/js/main.24564f9f.chunk.js** and **https://reduction-admin.github.io/react-reduction/static/js/2.f4291240.chunk.js**.

Why is that.. and what is the solution for it ??

**Comment by simsim0709** [comment]
Oh sorry, I don't have any experience of using this app with tomcat.

But, it might be helpful for you.

https://stackoverflow.com/questions/41246261/react-routing-is-able-to-handle-different-url-path-but-tomcat-returns-404-not-av/41249464#41249464

https://facebook.github.io/create-react-app/docs/deployment#serving-apps-with-client-side-routing
